### ISSUE TITLE
东方头条.py里面的from comments import generate_a_comment

### ISSUE THREAD

**Issue by 51f** [xingag/app_spider#1]
from comments import generate_a_comment
应该安装哪个模块?

运行报找不到模块错误.我发现目录下文件也没有以comments命名的包或模块.
ModuleNotFoundError: No module named 'comments'

**Comment by xingag** [comment]
这是一个随机产生一条评论的一个工具类，忘记删除了，可以注释掉先

**Comment by li497558599** [comment]
device_1 = Android('c54613d')   这是什么意思  能加上注释吗？

**Comment by li497558599** [comment]
raise DeviceConnectionError("device not ready")
airtest.core.error.DeviceConnectionError: 'device not ready'

**Comment by xingag** [comment]
> ```
> raise DeviceConnectionError("device not ready")
> ```
> airtest.core.error.DeviceConnectionError: 'device not ready'

这句话就是实例化一台设备对象【需要通过adb获取设备id】
