### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'home'

### ISSUE THREAD

**Issue by li497558599** [xingag/app_spider#2]
这种情况是怎么回事呢？ 
![企业微信截图_1553577207730](https://user-images.githubusercontent.com/24949780/54972993-04db1c00-4fc9-11e9-9d0b-7fbedff61688.png)

python小白  谢谢

**Comment by xingag** [comment]
home()方法是airtest库里面的类，需要先安装aritest库
`pip3 install airtest`

**Comment by li497558599** [comment]
![企业微信截图_15535808691341](https://user-images.githubusercontent.com/24949780/54975265-85057f80-4fd1-11e9-8ba9-b0b6c22c738c.png)
安装了这个库啊

**Comment by li497558599** [comment]
![企业微信截图_15535808691341](https://user-images.githubusercontent.com/24949780/54975296-a49ca800-4fd1-11e9-8006-068e04ed2c26.png)
这个库之前已经安装过了

**Comment by xingag** [comment]
> ![企业微信截图_15535808691341](https://user-images.githubusercontent.com/24949780/54975296-a49ca800-4fd1-11e9-8006-068e04ed2c26.png)
> 这个库之前已经安装过了

那就是是兼容的问题了，我用测试的小米4和MuMu模拟器是没问题的。

**Comment by li497558599** [comment]
好的  谢谢  不过我看这个源码里边和在知乎上的有不同的地方  知乎上是有一个start_my_app函数   这里边直接写的start_my_app()

**Comment by xingag** [comment]
start_my_app()是我自己写的函数；其实api有一个相同的方法，但是针对部分设备不兼容

**Comment by li497558599** [comment]
好的  我改改试试  另外utils文件夹里边少个__init__.py  否则无法导入

**Comment by xingag** [comment]
> 好的 我改改试试 另外utils文件夹里边少个__init__.py 否则无法导入

新建普通python项目，就不需要__init__.py文件的
