### ISSUE TITLE
请问报这种错误要怎么办You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission

### ISSUE THREAD

**Issue by qgqceo** [xingag/app_spider#4]
`[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/Users/allen/Library/Android/sdk/platform-tools/adb -P 5037 -s 34874d090704 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag'; Code: '1'
[debug] [W3C] Error: Command '/Users/allen/Library/Android/sdk/platform-tools/adb -P 5037 -s 34874d090704 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 1
`

**Comment by xingag** [comment]
这个应该是需要开发者模式下容许调试，需要打开一下
