### ISSUE TITLE
微信朋友圈运行报错

### ISSUE THREAD

**Issue by skVPN** [xingag/app_spider#5]
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=16663): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0C3750F0>: Failed to establish a new connection: [WinError 10061] ▒▒▒▒Ŀ▒▒▒▒▒▒▒▒▒▒▒ܾ▒▒▒▒޷▒▒▒▒ӡ▒'))

![image](https://user-images.githubusercontent.com/42835790/61508875-81818280-aa1e-11e9-92f1-af328e0179b6.png)

**Comment by xingag** [comment]
试试加一段休眠
