### ISSUE TITLE
微视不能自动跳转到下个app

### ISSUE THREAD

**Issue by dingxiaolong** [xingag/app_spider#7]
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=14800): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1129a4090>: Failed to establish a new connection: [Errno 61] Connection refused'))
[09:08:59][DEBUG]<airtest.core.android.adb> /usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 926QADUP2239U forward --remove tcp:14927
产生异常了
产生异常了
网络链接HTTPConnection走到了error里面,请问这个是什么原因呢

**Comment by xingag** [comment]
要跳转到哪个App？

**Comment by dingxiaolong** [comment]
不好意思是我描述错误了,是不能跳转到下一个视频播放,我看代码里面写的是播放完成一个自动滚动到下一个视频的

**Comment by xingag** [comment]
这个你做一下滑动就可以了，从底部坐标点往顶部坐标点方向滑动就可以

**Comment by dingxiaolong** [comment]
# 滑动到下一个视频
 self.poco.swipe([0.5, 0.8], [0.5, 0.1], duration=0.2)

大佬,我是直接运行你的源码,我看代码里面是写滚动了的,只是报了上面那个我刚开始说的错误才没滑动,我接触python没多久,看到这个demo挺有意思的就想先运行成功了,然后自己再仿写一下的..😀

**Comment by xingag** [comment]
这个异常我也没有遇到过，应该不是必现吧
